In [1]:
# Useful for Arrays and Basic numerical,statistical, Linear algebra functions
import numpy as np

In [3]:
# Elements are of same type, Indexed by tupels
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
### Alternative ways

#1
a = np.array(((1,2),(3,4),(5,6)))
print(a)

#2
a = np.array([[1,2],[3,4],[5,6]],dtype=float)
print(a)

#3
a = np.array([[1,2],[3,4],[5,6]],dtype=complex)
print(a)

#4
a = np.zeros((2,4))
print(a)

#5
a = np.ones((2,4))
print(a)

#6
a = np.empty((2,4))
print(a)


#7
a = np.identity(4)
print(a)


#8
a = np.eye(2,4)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [29]:
a = np.ones((2,4))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

a = np.ones((2,4,4))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
(2, 4)
8
float64
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 4, 4)
32
float64


In [36]:
a = np.ones((2,4))
print(a)

b = a.reshape(4,2)
print(b)

print(b.transpose())


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
## Indexing/Slicing 
#A[start:stop:step]

a = np.array([[1,2],[3,4],[5,6]])
print(a)

print(a[0]) #Row
print(a[0][1]) #Element
print(a[0:2]) #Rows
print(a[0:2,1]) #Rows and column

a = np.array([[  1,   2,  10,  -3,   9],
       [  3,   4, 100,   0, -32],
       [ 11,  12,  13,  14,  15],
       [ 21,  22,  23,  24,  25]])

print(a[::3,])

b = a[0:2,1:]
print(b)

b[0][0] = 323
print(b)
print(a)

# Slicings on lists and tuples create new objects,
# but slicing operation on an array creates a view on the original array

[[1 2]
 [3 4]
 [5 6]]
[1 2]
2
[[1 2]
 [3 4]]
[2 4]
[[ 1  2 10 -3  9]
 [21 22 23 24 25]]
[[  2  10  -3   9]
 [  4 100   0 -32]]
[[323  10  -3   9]
 [  4 100   0 -32]]
[[  1 323  10  -3   9]
 [  3   4 100   0 -32]
 [ 11  12  13  14  15]
 [ 21  22  23  24  25]]


In [81]:
#Mathematical functions
#a = np.array(range(1,10))
#print(a)

a= np.array([[1,2],[3,4],[5,6]])
print(a)

print("\n Sine: \n",np.sin(a))
print("\n Square root: \n",np.sqrt(a))
print("\n Log: \n",np.log(a))
print("\n Mean: \n",np.mean(a))
print("\n variance: \n",np.var(a))
print("\n Minimum: \n",np.min(a))
print("\n Maximum: \n",np.max(a))
print("\n Maximum of columns: \n",np.max(a,axis=0))
print("\n Maximum of rows: \n",np.max(a,axis=1))

[[1 2]
 [3 4]
 [5 6]]

 Sine: 
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

 Square root: 
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

 Log: 
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]

 Mean: 
 3.5

 variance: 
 2.9166666666666665

 Minimum: 
 1

 Maximum: 
 6

 Maximum of columns: 
 [5 6]

 Maximum of rows: 
 [2 4 6]
